version: '3.1'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    links:
      - phpfpm
    volumes:
      - ./nginx/conf.d/default.conf/:/etc/nginx/conf.d/default.conf
      - ./logs/nginx/:/var/log/nginx/
      - ./www/html/:/var/www/html/
    network_mode: bridge
  phpfpm:
    build: phpfpm/
    container_name: phpfpm
    links:
      - mysql
    ports:
      - 9000:9000
    volumes:
      - ./www/html/:/var/www/html/
    network_mode: bridge
  mysql:
    image: mariadb
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    network_mode: bridge
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports: 
      - 8888:80
    links:
      - mysql:db
    network_mode: bridge
